import { Manrope } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

const manrope = Manrope({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${manrope.className}  h-full antialiased`}>
      <body>
        <Navbar />
        {children}
      <Footer />
        <Toaster/>
      </body>

    </html>
  );
}
